### ISSUE TITLE
Can only see submissions email in CP.

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#10]
Again, trying to confirm a message in the spam queue is actually spam but I can't see the persons name or more importaly the content of the message.
![screenshot-www andersonhemmat com-2020 09 16-09_00_17](https://user-images.githubusercontent.com/16004958/93355237-163a6880-f7fb-11ea-97f8-30112c79075e.png)

The config for the form looks like this:
```
	'quick_contact' => [
            'author_field' => 'first_name',
	    'email_field' => 'email',
            'content_field' => 'q_message',
        ],
```
The form:
```
    fields:
      -
        handle: first_name
        field:
          type: text
          width: 50
          listable: true
          display: 'First Name'
          validate: required
      -
        handle: email
        field:
          type: text
          width: 50
          listable: true
          display: Email
          validate: required|email
      -
        handle: q_message
        field:
          type: textarea
          listable: hidden
          display: Message
          validate: required
```
